### ISSUE TITLE
ETA on missing guidelines

### ISSUE THREAD

**Issue by Whip** [material-components/material-components#109]
I've been waiting for over a month, there are a few pages like Bottom sheets, progress indicators that are missing the Guidelines in the docs. Its been saying 'coming soon' forever. How long will these take? Can you give us an ETA?

![image](https://user-images.githubusercontent.com/11595460/191656730-ec198dff-a22b-4129-a3a8-ceb279f7962c.png)

**Comment by leticiarossi** [comment]
Thank you for your interest and apologies we usually can't give exact dates of what may be labeled as coming soon. Those are frequently things in actively development that are released as soon as they're ready. The ones you mentioned as well as many other updates have landed on https://m3.material.io/ since this issue was opened
