### ISSUE TITLE
There's no Backdrop code, but the website says it does 

### ISSUE THREAD

**Issue by feinstein** [material-components/material-components#43]
The Material Design specs website says there's code available for a Backdrop, but when we click the link, there's a "coming soon" message on the git repo.

**Comment by kfranqueiro** [comment]
Can you clarify where you saw misleading information on the site? The backdrop page says "planned" for web under implementation. https://material.io/design/components/backdrop.html#implementation

Edit: Or, can you clarify which platform you were looking at? (Apologies, I initially mistook which repository this was reported under.)

**Comment by feinstein** [comment]
Yes, I am sorry I wasn't clear, I meant for the Flutter link.

**Comment by kfranqueiro** [comment]
Flutter provides guidance for implementing a Backdrop, rather than providing an out-of-the-box component, because its implementation may vary depending on a particular application's implementation details.

You can find the guidance documentation here: https://github.com/material-components/material-components-flutter/blob/develop/docs/components/backdrop.md

I've forwarded this report to the material.io site team to update the link. Thanks for reporting it.

**Comment by feinstein** [comment]
Interesting, usually when there are multiple ways of using a Widget, the Flutter team makes several widgets, like DrawerHeader and UserAccountDrawerHeader, but I guess backdrop must be more complicated than that.

**Comment by willlarche** [comment]
@feinstein Sorry for the confusion. Backdrop is an advanced component which means it doesn’t make sense to make a universal widget for it. You can read why and what you can do to make your own in https://github.com/material-components/material-components-flutter/blob/develop/docs/components/backdrop.md

**Comment by willlarche** [comment]
Hope that helps!

**Comment by feinstein** [comment]
Thanks Will, I will read it asap.

PS: Big fan of you on the Boring Show

**Comment by willlarche** [comment]
Omg! You’re so kind. Thank you. If you need anything else, do write. larche@google.com
